name: Build Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'bjet-release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      with: 
        script: |
          const now = new Date().toISOString().slice(0,10).replace(/-/g, ''); // YYYYMMDD
          const counter = '${{ steps.increment_counter.outputs.counter }}';
          const tagName = `v${now}-${counter}`;
          console.log(`Creating tag: ${tagName}`);
          github.rest.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tagName,
            message: `Release ${tagName}`, // Optional tag message
            object: context.sha // SHA of the commit to tag
          });
