name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Release to GitHub
      - uses: ncipollo/release-action@v1
        with:
          tag_name: bjet_v*
          release: bjet_v*
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
