name: Build Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'bjet-release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
